const level1 = new Level(
  [
    new Enemy("assets/png/enemy/enemyWalk/enemyWalk1.png"),
    new Enemy("assets/png/enemy/enemyWalk/enemyWalk1.png"),
    new Enemy("assets/png/enemy/enemyWalk/enemyWalk1.png"),
  ],
  new Boss("assets/png/boss/bossWalk/bossWalk1.png", 3000),
  [
    new Background("assets/png/background/bright/bg.png", 0),
    new Background("assets/png/background/bright/bg.png", 710),
    new Background("assets/png/background/bright/bg.png", 710 * 2),
    new Background("assets/png/background/bright/bg.png", 710 * 3),
    new Background("assets/png/background/bright/bg.png", 710 * 4),
    new Mountain("assets/png/background/bright/mountains.png", 0),
    new Mountain("assets/png/background/bright/mountains.png", 710),
    new Mountain("assets/png/background/bright/mountains.png", 710 * 2),
    new Mountain("assets/png/background/bright/mountains.png", 710 * 3),
    new Mountain("assets/png/background/bright/mountains.png", 710 * 4),
    new Background("assets/png/background/bright/wall@windows.png", 0),
    new Background("assets/png/background/bright/wall@windows.png", 710),
    new Background("assets/png/background/bright/wall@windows.png", 710 * 2),
    new Background("assets/png/background/bright/wall@windows.png", 710 * 3),
    new Background("assets/png/background/bright/wall@windows.png", 710 * 4),
    new Background("assets/png/background/bright/candeliar.png", 0),
    new Background("assets/png/background/bright/candeliar.png", 710),
    new Background("assets/png/background/bright/candeliar.png", 710 * 2),
    new Background("assets/png/background/bright/candeliar.png", 710 * 3),
    new Background("assets/png/background/bright/candeliar.png", 710 * 4),
    new Background("assets/png/background/bright/floor.png", 0),
    new Background("assets/png/background/bright/floor.png", 710),
    new Background("assets/png/background/bright/floor.png", 710 * 2),
    new Background("assets/png/background/bright/floor.png", 710 * 3),
    new Background("assets/png/background/bright/floor.png", 710 * 4),
    new Background("assets/png/background/bright/dragon.png", 0),
    new Background("assets/png/background/bright/dragon.png", 710),
    new Background("assets/png/background/bright/dragon.png", 710 * 2),
    new Background("assets/png/background/bright/dragon.png", 710 * 3),
    new Background("assets/png/background/bright/dragon.png", 710 * 4),
    new Background("assets/png/background/bright/columns&falgs.png", 0),
    new Background("assets/png/background/bright/columns&falgs.png", 710),
    new Background("assets/png/background/bright/columns&falgs.png", 710 * 2),
    new Background("assets/png/background/bright/columns&falgs.png", 710 * 3),
    new Background("assets/png/background/bright/columns&falgs.png", 710 * 4),
  ]
);
