const level1 = new Level(
  [
    new Enemy("assets/png/enemy/enemyWalk/enemyWalk1.png"),
    new Enemy("assets/png/enemy/enemyWalk/enemyWalk1.png"),
    new Enemy("assets/png/enemy/enemyWalk/enemyWalk1.png"),
  ],
  [
    new Minion("assets/png/enemy/enemyWalk/enemyWalk1.png"),
    new Minion("assets/png/enemy/enemyWalk/enemyWalk1.png"),
    new Minion("assets/png/enemy/enemyWalk/enemyWalk1.png"),
  ],
  new Boss("assets/png/boss/bossWalk/bossWalk1.png", 700),
  [
    //COINSET 1
    new Coin("assets/png/coin/gold1.png", 230, 180),
    new Coin("assets/png/coin/gold1.png", 250, 120),
    new Coin("assets/png/coin/gold1.png", 300, 90),
    new Coin("assets/png/coin/gold1.png", 350, 75),
    new Coin("assets/png/coin/gold1.png", 400, 90),
    new Coin("assets/png/coin/gold1.png", 450, 120),
    new Coin("assets/png/coin/gold1.png", 470, 180),
    //COINSET 2
    new Coin("assets/png/coin/gold1.png", 1430, 180),
    new Coin("assets/png/coin/gold1.png", 1450, 120),
    new Coin("assets/png/coin/gold1.png", 1500, 90),
    new Coin("assets/png/coin/gold1.png", 1550, 75),
    new Coin("assets/png/coin/gold1.png", 1600, 90),
    new Coin("assets/png/coin/gold1.png", 1650, 120),
    new Coin("assets/png/coin/gold1.png", 1670, 180),
    //COINSET 3
    new Coin("assets/png/coin/gold1.png", 2230, 180),
    new Coin("assets/png/coin/gold1.png", 2250, 120),
    new Coin("assets/png/coin/gold1.png", 2300, 90),
    new Coin("assets/png/coin/gold1.png", 2350, 75),
    new Coin("assets/png/coin/gold1.png", 2400, 90),
    new Coin("assets/png/coin/gold1.png", 2450, 120),
    new Coin("assets/png/coin/gold1.png", 2470, 180),
  ],
  [
    new Background("assets/png/background/bright/bg.png", 0),
    new Background("assets/png/background/bright/bg.png", 719),
    new Background("assets/png/background/bright/bg.png", 719 * 2),
    new Background("assets/png/background/bright/bg.png", 719 * 3),
    new Background("assets/png/background/bright/bg.png", 719 * 4),
    new Mountain("assets/png/background/bright/mountains.png", 0),
    new Mountain("assets/png/background/bright/mountains.png", 719),
    new Mountain("assets/png/background/bright/mountains.png", 719 * 2),
    new Mountain("assets/png/background/bright/mountains.png", 719 * 3),
    new Mountain("assets/png/background/bright/mountains.png", 719 * 4),
    new Mountain("assets/png/background/bright/mountains.png", 719 * 5),
    new Mountain("assets/png/background/bright/mountains.png", 719 * 6),
    new Mountain("assets/png/background/bright/mountains.png", 719 * 7),
    new Background("assets/png/background/bright/wall@windows.png", 0),
    new Background("assets/png/background/bright/wall@windows.png", 719),
    new Background("assets/png/background/bright/wall@windows.png", 719 * 2),
    new Background("assets/png/background/bright/wall@windows.png", 719 * 3),
    new Background("assets/png/background/bright/wall@windows.png", 719 * 4),
    new Background("assets/png/background/bright/candeliar.png", 0),
    new Background("assets/png/background/bright/candeliar.png", 719),
    new Background("assets/png/background/bright/candeliar.png", 719 * 2),
    new Background("assets/png/background/bright/candeliar.png", 719 * 3),
    new Background("assets/png/background/bright/candeliar.png", 719 * 4),
    new Background("assets/png/background/bright/floor.png", 0),
    new Background("assets/png/background/bright/floor.png", 719),
    new Background("assets/png/background/bright/floor.png", 719 * 2),
    new Background("assets/png/background/bright/floor.png", 719 * 3),
    new Background("assets/png/background/bright/floor.png", 719 * 4),
    new Background("assets/png/background/bright/dragon.png", 0),
    new Background("assets/png/background/bright/dragon.png", 719),
    new Background("assets/png/background/bright/dragon.png", 719 * 2),
    new Background("assets/png/background/bright/dragon.png", 719 * 3),
    new Background("assets/png/background/bright/dragon.png", 719 * 4),
    new Background("assets/png/background/bright/columns&falgs.png", 0),
    new Background("assets/png/background/bright/columns&falgs.png", 719),
    new Background("assets/png/background/bright/columns&falgs.png", 719 * 2),
    new Background("assets/png/background/bright/columns&falgs.png", 719 * 3),
    new Background("assets/png/background/bright/columns&falgs.png", 719 * 4),
  ]
  
);
